spring:
  profiles: data-local
  datasource:
    # yml配置中，不能使用转义符
    url: jdbc:mysql://182.92.211.147:3306/es_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&autoReconnectForPools=true&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    userName: root
    password: 0522$Rfv
    sql-script-encoding: utf-8
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,slf4j,wall
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    useGlobalDataSourceStat: true
    logSlowSql: true
  transaction:
    rollback-on-commit-failure: on

  messages:
    basename: messages/i18n
    encoding: UTF-8
    cache-duration: -1


  redis:
    host: 182.92.211.147
    port: 6379
    password: tailgrass
    jedis:
      pool:
        max-active: 8
        max-idle: 8
logging:
  config: classpath:log4j2-local.xml